### ISSUE TITLE
Cxx community plugin sonar scan analysis taking too long to complete

### ISSUE THREAD

**Issue by fayaz988** [SonarOpenCommunity/sonar-cxx#2502] opened 2023-04-05 07:31 UTC
i am using sonar community 9.9 LTS
sonar community cxx 4.1.3 jar
it is taking too long to complete sonar scan analysis after report. xml generation because of it big project but
is there any we can make it faster.

Run sensors on project
```
INFO: Sensor CXX [cxx]
INFO: Sensor CXX [cxx] (done) | time=9859297ms
INFO: Sensor CXX Cppcheck report import [cxx] 
```

**Comment by guwirth** [comment] 2023-04-12 06:26
Hi @fayaz988,

from your description I understand that the overall time is high.

can you please turn debug info on to see in which sensor the time is used up?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Sensor `Sensor CXX [cxx]` is the squid sensor and not the Cppcheck sensor. 

> because of it big project but

How big is your project (LoC)?

> is there any we can make it faster

You can try https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.squid.disabled

Regards,

**Comment by Nekto89** [comment] 2023-05-03 19:19
@guwirth Is there any difference how plugin analyzes input depending on SonarQube version? On SQ 8.9 local analysis takes about 9 minutes, and on SQ 9.9 it's almost 3 hours. I'll try enabling debug information on next run.

**Comment by Nekto89** [comment] 2023-05-04 07:41
My project is 1.5M lines of code.

00:15:02.892 INFO: Sensor CXX [cxx] (done) | time=9602093ms
00:15:05.005 INFO: Sensor CXX Cppcheck report import [cxx] (done) | time=2113ms	
00:16:12.573 INFO: Sensor CXX Visual C++ compiler report import [cxx] (done) | time=67568ms
00:16:19.235 INFO: Sensor CXX Bullseye coverage report import [cxx] (done) | time=6662ms

From log I don't see any specific place that takes lots of time individually. There are lots of 
"Not enough content in '.......h' to have CPD blocks, it will not be part of the duplication detection"
"CPD error in file '......h' at line:XXXX, column:XX"

I've tried enabling profiling.xml
-X -Dsonar.verbose=true -Dsonar.showProfiling=true
but I can't find it anywhere.

**Comment by guwirth** [comment] 2023-05-04 19:12
> Is there any difference how plugin analyzes input depending on SonarQube version? On SQ 8.9 local analysis takes about 9 minutes, and on SQ 9.9 it's almost 3 hours. I'll try enabling debug information on next run.

@Nekto89
Are you using the same cxx plugin version with both SQ versions?
Is only the SQ version different?
At least on our integration server the time is not that different, sample 
https://github.com/SonarOpenCommunity/sonar-cxx/actions/runs/4797926536

**Comment by guwirth** [comment] 2023-05-04 19:14
> "Not enough content in '.......h'

@Nekto89 means typically only that the file is too small.

**Comment by Nekto89** [comment] 2023-05-04 23:05
First 21:35:00.946 DEBUG: process unit
Last 21:37:56.186 DEBUG: process unit 
So it's just 3 minutes?
Together there are 13753 entries "process unit" which seems to be just the number of C++ files.

Then there are only CPD error in file/Not enough content/Highlighting error until 
00:15:02.892 INFO: Sensor CXX [cxx] (done) | time=9602093ms
Does this somehow help? Should I run with some additional verbose options?

**Comment by Nekto89** [comment] 2023-05-05 14:07
without heavy squid part as expected it only takes 3+ minutes

15:50:55.504 INFO: EXECUTION SUCCESS
15:50:55.504 INFO: ------------------------------------------------------------------------
15:50:55.504 INFO: Total time: 3:24.549s
15:50:55.547 INFO: Final Memory: 25M/2048M

But the result on server doesn't have lots of useful things so it is not a solution for my usecase.

**Comment by guwirth** [comment] 2023-05-05 15:58
@Nekto89
- means SQ 9.9, scanner 4.8, Java 17, cxx plugin 2.1.0.428 is slow. Which OS are you using?
- means SQ 8.9, scanner 4.6.2, Java 11, cxx plugin 2.1.0.428 is fast?
Correct?

**Comment by Nekto89** [comment] 2023-05-05 16:41
I've reran on SQ 8.9 again now to recheck. I've also sorted both log files without timestamps to try and see any differences (regex r"\d{2}\:\d{2}:\d{2}\.\d{3}(.*)" to get rid of timestamps). There is nothing useful related to C++. All data/metrics are completely the same, just in different order.

Java 17.0.7 Azul Systems, Inc. (64-bit)
C++ (Community) 2.1.0.428 (cxx)
Windows Server 2019 (Version 1809, OS Build 17763.3887)
SONAR_SCANNER_OPTS=-Xmx5g -Xms2g

Community 8.9.5.50698 - INFO: Sensor CXX [cxx] (done) | time=256122ms
Community 9.9.1.69595 - INFO: Sensor CXX [cxx] (done) | time=9602093ms

**Comment by guwirth** [comment] 2023-05-05 19:32
Hi @Nekto89,

maybe you can try with latest SQ 9.9.1, they fixed two performance issues:
- https://community.sonarsource.com/t/sonarqube-9-9-1-lts-released/90049
- https://sonarsource.atlassian.net/browse/SONAR-18872?jql=project%20%3D%2010139%20AND%20fixVersion%20%3D%2014051
- https://sonarsource.atlassian.net/browse/SONAR-18472?jql=project%20%3D%2010139%20AND%20fixVersion%20%3D%2014051

Because rest seems to be the same it must be something with new SQ 9.9 LTS.

Regards,

**Comment by Nekto89** [comment] 2023-05-06 18:07
I've managed to somehow start Visual VM and run sampler on running scanner. Can it be that the slowdown is somehow caused by saving *.pb files after the scan? In Windows Explorer these files are created very slowly. And in sampler I see that it already took more time than analysis itself and the number continues to grow.

![image](https://user-images.githubusercontent.com/4276548/236639893-66e6ab95-b62c-46d0-9dd0-14b24e5e3fb9.png)

![image](https://user-images.githubusercontent.com/4276548/236640030-2ea09fdd-09d7-400c-b84e-cde5e280e01f.png)

**Comment by guwirth** [comment] 2023-05-06 18:49
Hi @Nekto89,

The .pb files are not created by the cxx plugin. Maybe they are from the scanner and the new cache functionality? Think you have to ask in the Sonar community https://community.sonarsource.com/ what are they for.

Did you try with 9.9.1 if scan is still slow?

Regards,

**Comment by Nekto89** [comment] 2023-05-06 19:13
> Hi @Nekto89,
> 
> The .pb files are not created by the cxx plugin. Maybe they are from the scanner and the new cache functionality? Think you have to ask in the Sonar community https://community.sonarsource.com/ what are they for.
> 
> Did you try with 9.9.1 if scan is still slow?
> 
> Regards,

Yes, I was using 9.9.1.69595 from the start. I just was calling it 9.9 because that's how it's labeled everywhere if you don't go into details.

InputFile is created here as far as I understand.
https://github.com/SonarOpenCommunity/sonar-cxx/blob/82350cdbc28327e561dc44d4821ab240dfb1d861/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxSquidSensor.java#LL423C9-L423C108

So you suspect that this might be the problem somewhere in sonar.api implementation?
https://github.com/SonarSource/sonarqube/tree/9.9.1.69595/sonar-plugin-api-impl/src/main/java/org/sonar/api/batch/fs/internal

**Comment by Nekto89** [comment] 2023-05-06 19:55
for history: that's how it looks at 8.9.5 run

![image](https://user-images.githubusercontent.com/4276548/236644089-bc378783-51ef-4d3b-a74c-3e577932dbba.png)

**Comment by guwirth** [comment] 2023-05-08 14:48
Hello @Nekto89,

thanks for your investigation.

When I look at the answers I have received so far, the plugin version is the same, only the SQ version is different. For me that means: same plugin code, same API calls in same order. There must be a change in the API library or SQ.

The measurements you provide show the `CxxSquidSensor.save` function.  I never looked in detail, but it seems that the `saveMetrics `functions use protocol buffer files (.pb) to store the result and pass it to the server?

The main difference in SQ 9.9 seems to be the ability to cache results from previous analyses. Maybe it has something to do with that?

Another difference I see is this `MutableFileSystem.inputFile`:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/82350cdbc28327e561dc44d4821ab240dfb1d861/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxSquidSensor.java#L418

![grafik](https://user-images.githubusercontent.com/6077367/236854194-811d9edc-dbb3-4da9-8ba3-75777ab94d4b.png)

Maybe have to verify how other plugins are doing this iteration over input files to save the metrics?

Regards,

**Comment by Nekto89** [comment] 2023-05-08 16:49
I'm not a Java developer at all, but do I understand correctly that each time it starts search from first file? O(N²)? And search is based on calls to real filesystem instead of checking file paths?

**Comment by guwirth** [comment] 2023-05-09 06:35
Hi @Nekto89,

> it starts search from first file? O(N²)

maybe you are right, it’s most likely this line
https://github.com/SonarOpenCommunity/sonar-cxx/blob/82350cdbc28327e561dc44d4821ab240dfb1d861/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxSquidSensor.java#L423

Strange thing is that this is fast with SQ 8.9?

I read somewhere that the new scanners are reading all files in the root folder now. Are there many files in your project which are maybe ignored in older version, e.g intermediate compiler/linker files (.obj, …)?

Regards,

**Comment by Nekto89** [comment] 2023-05-09 09:19
> Hi @Nekto89,
> I read somewhere that the new scanners are reading all files in the root folder now. Are there many files in your project which are maybe ignored in older version, e.g intermediate compiler/linker files (.obj, …)?

I don't have lots of additional files in "sonar.projectBaseDir=Libraries" (15,257 Files, 2,327 Folders), but folder with sonar-project.properties file has also .git subfolder and several additional folders with test data in different formats (~115k files).
I've tried moving sonar-project.properties to Libraries subfolder and changing sonar.projectBaseDir to "." but the speed is the same.

**Comment by guwirth** [comment] 2023-05-09 10:00
Hi @Nekto89,

maybe you can try with https://github.com/SonarOpenCommunity/sonar-cxx/pull/2520. I'm doing it with `hasPath` now, like other plugins.
Download is here: https://github.com/SonarOpenCommunity/sonar-cxx/suites/12769308245/artifacts/686739059

Regards,

**Comment by Nekto89** [comment] 2023-05-09 10:51
This looks much better on 9.9.1:
`Sensor CXX [cxx] (done) | time=610102ms`

**Comment by guwirth** [comment] 2023-05-09 18:56
Hi @Nekto89,

I merged it to https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/latest-snapshot

**old cxx V2.1.0.428**
```
Community 8.9.5.50698 - INFO: Sensor CXX [cxx] (done) | time=  256.122ms
Community 9.9.1.69595 - INFO: Sensor CXX [cxx] (done) | time=9.602.093ms
```
**new cxx V2.1.1.479**
```
Community 9.9.1.69595 - INFO: Sensor CXX [cxx] (done) | time=  610.102ms
```
but still slower…

Regards,

**Comment by guwirth** [comment] 2023-05-11 05:10
@Nekto89 can you support me by running Visual VM sampler on scanner again?

**Comment by guwirth** [comment] 2023-05-11 08:25
@Nekto89 by the way: How do you attach the Profiler to the scanner?

**Comment by Nekto89** [comment] 2023-05-11 08:36
> @Nekto89 can you support me by running Visual VM sampler on scanner again?

I've cleaned up all temporary files and returned back to using "sonar.projectBaseDir=Libraries". It shows the same performance as 8.9.5. I don't know why it was 610 seconds on my previous run - maybe Windows was doing something in the background.

So today
first run with sampler:
![image](https://github.com/SonarOpenCommunity/sonar-cxx/assets/4276548/f15ab1c9-0e17-4427-9a52-9edcf2eef403)

second run without sampler:
10:29:30.384 INFO: Sensor CXX [cxx] (done) | time=258745ms

**Comment by Nekto89** [comment] 2023-05-12 08:34
> @Nekto89 by the way: How do you attach the Profiler to the scanner?

I just launch sonar scanner and VisualVM sees it.
I had to manually specify visualvm_jdkhome in conf file.

![image](https://github.com/SonarOpenCommunity/sonar-cxx/assets/4276548/b0af690d-3ce1-43dc-9a39-dd9873313771)

**Comment by guwirth** [comment] 2023-05-17 11:29
Hi @Nekto89, there is another try to improve the performance: #2525

You can download the JAR from here:
https://github.com/SonarOpenCommunity/sonar-cxx/suites/12954625861/artifacts/700507885

Because there are many boundary conditions with impact on the performance, would be good to get also feedback from you.

Thx and regards,

**Comment by Nekto89** [comment] 2023-05-17 15:34
> Hi @Nekto89, there is another try to improve the performance: #2525
> 
> You can download the JAR from here: https://github.com/SonarOpenCommunity/sonar-cxx/suites/12954625861/artifacts/700507885
> 
> Because there are many boundary conditions with impact on the performance, would be good to get also feedback from you.
> 
> Thx and regards,
I've already moved my local environment to newer commit, so source code is very slightly different. Tried 2 runs.

* C++ (Community) 2.1.1.483 (cxx)

17:13:21.432 INFO: Sensor CXX [cxx] (done) | time=256371ms
17:22:54.431 INFO: Sensor CXX [cxx] (done) | time=260306ms

Performance seems to be on par with previous fix.

**Closed** 2023-05-20 10:51 UTC
Labels: bug

**Comment by guwirth** [comment] 2023-05-20 12:22
@Nekto89 @fayaz988 fixed with https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.1.1
