### ISSUE TITLE
PC-Lint issues are not displayed properly on SonarQube UI

### ISSUE THREAD

**Issue by Wankhadess** [SonarOpenCommunity/sonar-cxx#2326] opened 2022-03-01 06:58 UTC
**Describe the bug**
When PC lint creates a reference message (L893, L891) to another massage, the reference message is placed next to the main issue in the PC-Lint export file so it’s easy to locate the main Issue . But When importing this to sonarqube the connection between the reference and the original message is lost, since the issues are placed anywhere in the source code.

**Expected behavior**
As Issue handled by Sonarqube is described in Official doc : [Issues | SonarQube Docs](https://docs.sonarqube.org/8.9/user-guide/issues/) refer Understanding issue context
The Reference message should points out the main Issue in SonarQube UI so that it can be easy handled.

**Steps to create Issue**

Create PC-Lint Report. xml with Some reference messages which points the main Issue message and pass it to SonarQube
When you click on reference messages on SonarQube UI it will not provide you the actual main Issue message which causing the additional reference messages.

**Desktop:**
OS: Windows
SonarQube version: 8.9.2 LTS
cxx plugin version: 2.0.4 (build 2835)
sonar-scanner version: 4.7

Let me known your Points on this or any other Information required from My end.

Regards

**Comment by guwirth** [comment] 2022-03-01 07:08
Hi @Wankhadess,

thanks for your feedback.

Could you provide a small sample to reproduce the issue please:
* source code snippet fitting to report
* small PC-Lint Report.xml with (one) main issue and (some) reference messages

Thanks

**Comment by Wankhadess** [comment] 2022-03-03 06:02
Hi @guwirth 

Test.c

100: int16 a = 10;
//lots of code without use of a;
141: a = 30;

PC-Lint_Report:
<issue file ="D:\Test.c" line = "141" number = "838" desc = "previous value assigned to &apos;a&apos; not used"/>
<issue file ="D:\Test.c" line = "100" number = "891" desc = "previous assignment is here"/>

**Comment by Wankhadess** [comment] 2022-03-03 06:04
Test.c

100: int16 a = 10;
//lots of code without use of a;
141: a = 30;


PC-Lint_Report:

issue file ="D:\Test.c" line = "141" number = "838" desc = "previous value assigned to &apos;a&apos; not used"/>
<issue file ="D:\Test.c" line = "100" number = "891" desc = "previous assignment is here"/

**Comment by guwirth** [comment] 2022-03-04 06:08
Hi @Wankhadess,

thanks for the sample.

Because reference message and message have the same format in the LOG file, it’s not possible to detect the difference. 

Supplemental messages are supported but they have a different format. Seems `type` is missing in your LOG file:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<doc>
<issue file =".\FileZip.cpp" line = "4" number = "1960" desc = "Violates MISRA C++ 2008 Required Rule 5-0-19, More than two pointer indirection levels used for type: 'struct _wireSAFEARRAY ***"/>
<issue file = ".\FileZip.cpp" line = "20" number = "1800" type = "supplemental" desc = "this is supplemental msg one."/>
<issue file = ".\FileZip.h" line = "20" number = "1801" type = "supplemental" desc = "this is supplemental msg two."/>
<issue file = "" line = "" number = "894" type = "supplemental" desc = "during specific walk FileZip.h:3:2 this is supplemental msg three."/>
<issue file =".\FileZip.h" line = "37" number = "950" desc = "Non-ANSI reserved word or construct: '__stdcall'"/>
<issue file = "" line="0" number = "934" type = "supplemental" desc = "during specific walk FileZip.cpp:4:2 this is supplemental msg three."/>
</doc>
```

Wiki: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.pclint.reportPaths

Code from sensor: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/pclint/CxxPCLintSensor.java

Regards,

**Comment by guwirth** [comment] 2022-03-15 11:53
Close it, seems to be solved.

**Closed** 2022-03-15 11:54 UTC
Labels: question
