### ISSUE TITLE
US: Add Measures / Complexity / Cognitive Complexity

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1297] opened 2017-11-11 20:06 UTC
Add Measures / Complexity / Cognitive Complexity:

![grafik](https://user-images.githubusercontent.com/6077367/32693034-ffa776d6-c723-11e7-9ed2-9e0709997b04.png)

**Comment by nathanaelg** [comment] 2017-11-12 23:56
I'm not sure if this is something community plugins can do, but this kind of thing would be super useful for seeing why something is marked as overly complex:

![image](https://user-images.githubusercontent.com/2712036/32704898-c8146da6-c871-11e7-8d98-c006684f266b.png)

https://next.sonarqube.com/sonarqube/project/issues?id=org.sonarsource.java%3Ajava&open=AV8Bj_lB7QShli31n-Rx&resolved=false

**Comment by ivangalkin** [comment] 2018-08-08 22:54
w.r.t. to missing complexity **metrics**: latest with #1514 they should work again
w.r.t. to the explanation of the complexity **checks**: it's a duplicate of #1494
I suggest to close this issue; Regards

**Closed** 2018-08-09 05:59 UTC
Labels: duplicate

**Comment by malisasmaz** [comment] 2019-02-26 11:09
> I'm not sure if this is something community plugins can do, but this kind of thing would be super useful for seeing why something is marked as overly complex:
> 
> ![image](https://user-images.githubusercontent.com/2712036/32704898-c8146da6-c871-11e7-8d98-c006684f266b.png)
> 
> https://next.sonarqube.com/sonarqube/project/issues?id=org.sonarsource.java%3Ajava&open=AV8Bj_lB7QShli31n-Rx&resolved=false

Hi,
I can not see details in my sonarqube like (incl 1 for nesting etc.) how can I see this?
My method's screenshot, I can not see why it is +11
![image](https://user-images.githubusercontent.com/5444250/53408624-fd2b5600-39cf-11e9-9157-046ee8dfb1cc.png)

**Comment by ivangalkin** [comment] 2019-02-26 11:51
@malisasmaz this feature was implemented in sonar-cxx-plugin version 1.2. So you have to update your plugin.
