### ISSUE TITLE
If a class has exported, then that class is not counted as a class by sonar-cxx parser

### ISSUE THREAD

**Issue by BalaVaranasi** [SonarOpenCommunity/sonar-cxx#1207] opened 2017-08-15 17:52 UTC
Hi,

     I have a VTK class called, "vtkPistonAlgorithm" which was an exported class so that users/clients can use this class in their code. 

class VTKACCELERATORSPISTON_EXPORT vtkPistonAlgorithm : public vtkAlgorithm
{
public:
  static vtkPistonAlgorithm *New();
  vtkTypeMacro(vtkPistonAlgorithm,vtkAlgorithm);
  void PrintSelf(ostream& os, vtkIndent indent);

.........
.........
};

when i run sonar-cxx profile on class, in the sonarqube results, it shows class count for "vtkPistonAlgorithm.h" file as "0" but it should show class count as 1. Because of this bug, "Complexity / Class" metric gives wrong results.

Can you provide any hack / fix for getting rid of this issue?

[vtkPistonAlgorithm.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1225880/vtkPistonAlgorithm.zip)

**Comment by guwirth** [comment] 2017-08-15 18:17
Hi @BalaVaranasir,
Think the problem is VTKACCELERATORSPISTON_EXPORT. You have to mock it to get a valid C++ syntax. Please read this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces. 
Regards,

**Comment by guwirth** [comment] 2017-08-17 06:04
@BalaVaranasi I close this. Please reopen if still an issue.

**Closed by guwirth** 2017-08-17 06:04 UTC
Labels: question
