### ISSUE TITLE
Import of VisualStudio compiler messages not working

### ISSUE THREAD

**Issue by Wankhadess** [SonarOpenCommunity/sonar-cxx#1852] opened 2020-04-23 11:20 UTC
Hi,

I want export warning from c++ msbuild.log file to sonarqube, using c++ community plugin,
after exporting, sonarqube has provided no result.

I’m using this process

**E:\BetaTesting_SCA_Suite\sonar-scanner-msbuild-4.7.1.2311-net46>SonarScanner.MSBuild.exe begin /k:"vsbuildlog"**

**E:\BetaTesting_SCA_Suite\sonar-scanner-msbuild-4.7.1.2311-net46>“C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe” “E:\BetaTesting_Testingframework\CustomCppcheckRules\cppcheck-1.87\cppcheck.sln” /t:rebuild /p:Configuration=Release;WarningLevel=3 /fileLogger /fileLoggerParameters:WarningsOnly;LogFile=E:\BetaTesting_Testingframework\CustomCppcheckRules\cppcheck-1.87\buildlog.log;Verbosity=detailed;Encoding=UTF-8**

**E:\BetaTesting_SCA_Suite\sonar-scanner-msbuild-4.7.1.2311-net46>SonarScanner.MSBuild.exe end**

After above process i got this output

**INFO: Sensor C++ (Community) SquidSensor [cxx] (done) | time=2188ms
INFO: Sensor C++ (Community) CxxCompilerVcSensor [cxx]
INFO: Searching reports by relative path with basedir ‘E:\BetaTesting_Testingframework\CustomCppcheckRules\cppcheck-1.87’ and search prop 'sonar.cxx.vc.reportPath’
INFO: Parser will parse ‘1’ report file(s)
INFO: Processing report 'E:\BetaTesting_Testingframework\CustomCppcheckRules\cppcheck-1.87\buildlog.log’
INFO: Parsing ‘Visual C++’ initialized with report ‘E:\BetaTesting_Testingframework\CustomCppcheckRules\cppcheck-1.87\buildlog.log’, Charset= 'UTF-8’
INFO: Using pattern : '(.>)?(?.)((?\d+))\x20:\x20warning\x20(?C\d+):(?.*)'
INFO: CXX-COMPILER-VC processed = 0
INFO: Sensor C++ (Community) CxxCompilerVcSensor [cxx] (done) | time=16640ms**

as you can see, no warnings are processed but, buildlog.log contains many warnings.

buildlog.log and sonarqube.analysis.xml file:
[analysis.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/4522110/analysis.zip)

I’m using **SonarQube Version 7.9.1
sonar-scanner-msbuild-4.7.1.2311-net46
C++ (Community) 1.3.1.1807 (cxx)**

Reference link: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers

when i use the **sonar.cxx.vc.regex=(.>)?(?.)\((?\d+)\)\x20:\x20warning\x20(?C\d+):(?.*)** property in **sonarqube.analysis.xml** file it hits the below error message

**Loading analysis properties from E:\BetaTesting_SCA_Suite\sonar-scanner-msbuild-4.7.1.2311-net46\SonarQube.Analysis.xml
Unable to read the SonarQube analysis settings file ‘E:\BetaTesting_SCA_Suite\sonar-scanner-msbuild-4.7.1.2311-net46\SonarQube.Analysis.xml’. Please fix the content of this file.**

But if you notice in the output after build, without providing regex property its using the below regex pattern.
**INFO: Using pattern : '(.>)?(?.)((?\d+))\x20:\x20warning\x20(?C\d+):(?.*)'**

Can you help me to resolve this Issue?

Regards
Sheetal

**Comment by guwirth** [comment] 2020-04-23 15:17
Hi @Wankhadess,

did you read this https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#microsofts-visual-studio-compiler?

```INI
# read settings
sonar.cxx.msbuild.reportPath=E:/BetaTesting_Testingframework/CustomCppcheckRules/cppcheck-1.87/buildlog.log
sonar.cxx.msbuild.charset=UTF-8

# read warnings
sonar.cxx.vc.reportPath=E:/BetaTesting_Testingframework/CustomCppcheckRules/cppcheck-1.87/buildlog.log
sonar.cxx.vc.charset=UTF-8
sonar.cxx.vc.regex=...
```

The CXX plugin is only tested with https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/.
We never tested it with `SonarScanner for MSBuild`.

Regards,

**Comment by guwirth** [comment] 2020-04-23 15:21
... and try to turn DEBUG info on https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

**Comment by Wankhadess** [comment] 2020-04-27 18:06
Hi @guwirth ,

Thanks for your response.

I have also run it with https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
but the Output is same.

sonar-project.properties 
[sonar-project.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/4541313/sonar-project.zip)


I think the issue is with the regex expression ,the regex provided in the documentation  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#microsofts-visual-studio-compiler is for Visual Studio 2010 - 2015 version and am using the Visual Studio 2017.

using this https://regex101.com/ I have checked that the regex "**(.>)?(?.)((?\d+))\x20:\x20warning\x20(?C\d+):(?.*)**"  am providing for my buildlog.log data was invalid.

I have taken the reference from https://github.com/SonarOpenCommunity/sonar-cxx/issues/1694 

Also, I have tried below regex which is valid 
**(.*>)?\x20*(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):\x20*(?<message>.*)\x20\[.*\]$** 
but am still not getting any result.
<img width="656" alt="debugreport" src="https://user-images.githubusercontent.com/64198883/80403525-58f7b480-88dd-11ea-948d-ec5a602e1b76.PNG">


Regards,
Wankhadess

**Comment by guwirth** [comment] 2020-04-28 06:32
Hi @Wankhadess ,

looking to the screenshot (using pattern...) I thing you have to double the backlash.

_Hint on https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#microsofts-visual-studio-compiler: You have to use additional escape sequences (\-> \\) for the regex property in the configuration file!_

Regards,

**Comment by Wankhadess** [comment] 2020-05-04 12:07
Hi @guwirth ,

I had tried using double backslash but the output is same. will you please check my Buildlog.log file to see whether regex am providing is correct or not.

<img width="482" alt="debugreport" src="https://user-images.githubusercontent.com/64198883/80964089-e2ebd400-8e2d-11ea-9d39-c4dfd5afca8a.PNG">

**Comment by SabapathyKannappan** [comment] 2020-05-05 14:37
I also experience the same issue, the warnings are not interpreted

**Comment by guwirth** [comment] 2020-05-06 08:44
@Wankhadess 

Think in general it should work, there are unit tests for it, but I will verify it again.
- https://github.com/SonarOpenCommunity/sonar-cxx/blob/master-1.3.x/cxx-sensors/src/test/java/org/sonar/cxx/sensors/compiler/vc/CxxCompilerVcSensorTest.java
- reports for testing: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master-1.3.x/cxx-sensors/src/test/resources/org/sonar/cxx/sensors/reports-project/compiler-reports

Looking into your build.log the messages look like this:
```
e:\betatesting_testingframework\customcppcheckrules\cppcheck-1.87\customrules\customrulesloaderandinitializer.h(62): warning C4100: 'settings': unreferenced formal parameter (compiling source file ..\customrules\customrulesloaderandinitializer.cpp) [E:\BetaTesting_Testingframework\CustomCppcheckRules\cppcheck-1.87\lib\cppcheck.vcxproj]
```
- format is: `file(line): warning Cid: message`
- you must use regex named groups `<file>, <line>, <id>, <message>`
- single process: you are running a single process, there is no process id at the beginning: `(.*>)?` is not needed
- your read msbuild.log as `UTF-8`; are you sure it's `UTF-8` and not `UTF-16`?
- To assign issues a file must be indexed, in the sample `e:\betatesting_testingframework\customcppcheckrules\cppcheck-1.87\customrules\customrulesloaderandinitializer.h`. Are you sure the file is indexed (verify in log file) and the file exists on this position on your HDD where the scanner is running?

**Comment by SabapathyKannappan** [comment] 2020-05-06 17:08
Hi, I too face a similar issue for a VC project. I use the reg ex "(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)". In the sonar scan log, i could see the log file is analyzed with this pattern, but it does not report the warnings in the sonar portal...

**Comment by guwirth** [comment] 2020-05-07 06:16
@SabapathyKannappan you must use regex named groups `<file>, <line>, <id>, <message>`

https://www.logicbig.com/tutorials/core-java-tutorial/java-regular-expressions/named-captruing-groups.html

**Comment by SabapathyKannappan** [comment] 2020-05-07 11:02
Yeah, i used the same named groups but there was a mistake from my side.. The build log had 800+ warnings (simulated). With the correct regex, I am able to grep very few warnings and report in Sonar based on Severity. The problem is, for other warnings in build log (not related the sources (.cpp/.h) of my application, the issue is not reported in Sonar. The question is, the sonar scan for compiler warnings do work only for warnings in the application source (.cpp) or other warnings (eg:   c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\ios(344): warning C4514: 'std::uppercase': unreferenced inline function has been removed [D:\test\TestCPPSonar\testproject\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj) too? There are 500+ warnings like this.

**Comment by guwirth** [comment] 2020-05-07 15:25
I created a sample: https://github.com/SonarOpenCommunity/sonar-cxx/pull/1858

It's working but I found some changes with VS2019:
* after file there is in newer VS versions line and column `file(line,column)` before `file(line)` only
* there is no blank after the position `file(line,column): warning` and not `file(line,column) : warning`
* In case of encoding UTF-8 msbuild adds an BOM. This is no problem for warnings not in the first line of the LOG file.
* `sonar.cxx.vc.regex=(.*>)?(?<file>.*)\\((?<line>\\d+),\\d+\\):\\x20warning\\x20(?<id>C\\d+):\\x20(?<message>.*)`

**Comment by guwirth** [comment] 2020-05-07 15:31
Hi @SabapathyKannappan, good to hear that it is working.

> sonar scan for compiler warnings do work only for warnings in the application source

SQ works like this:
1. indexing of files / read files matching a language file extension: only below baseDir
2. assigning issues to indexed files (or project): issues for unknown files are ignored

That's mostly what users wanna have. Think you don't wanna fix issues in Microsoft headers?

**Comment by guwirth** [comment] 2020-05-07 15:46
@Wankhadess in your case with 2017 below without column should work:
```properties
sonar.cxx.vc.regex=(.*>)?(?<file>.*)\\((?<line>\\d+)\\):\\x20warning\\x20(?<id>C\\d+):\\x20(?<message>.*)
```

**Comment by SabapathyKannappan** [comment] 2020-05-07 17:08
@guwirth - Thanks a lot for the reply.. yes, i do agree with the statement. Fix in msft headers not required.. but just checking if there is a way to detect those warnings and report that as a kind of minor/info category at SQ... I was trying with the parameter "sonar.cxx.includeDirectories" if it can help in any way...

**Comment by SabapathyKannappan** [comment] 2020-05-07 17:24
@guwirth : Is "indexing of files / read files matching a language file extension: only below baseDir" documented in Sonar ?.. I read the notes, but could not find this

**Comment by guwirth** [comment] 2020-05-07 19:09
@SabapathyKannappan you can’t find this explicit in the docu, maybe here implicit https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/. The point is that there is no API to add issues to unknown files (unknown = not indexed). The only exception is to add an issue to a project (without file).

**Comment by guwirth** [comment] 2020-05-08 08:15
@Wankhadess I close this, please reopen if still an issue.

**Closed by guwirth** 2020-05-08 08:15 UTC
Labels: question
