### ISSUE TITLE
sonar CXX plugin sonar scan can't finish when it found can't find resources 

### ISSUE THREAD

**Issue by liucc52** [SonarOpenCommunity/sonar-cxx#1588] opened 2018-11-14 01:52 UTC
sonar scan can't finish when it found can't find resources 

our  sonar scan stucked when it reports lots of warn 
can not find resources for '#include< QDir >'
can not find resources for '#include< QRecF >'

**Comment by guwirth** [comment] 2018-11-14 06:33
Hi,
which version of SQ and cxx plugin are you using?
Please provide LOG file (at least relevant parts).
Regards,

**Comment by liucc52** [comment] 2018-11-14 06:51
we are using sonarqube 7.3 cxx plugin 1.2
right now we find if our code have 
xx<xx::xxx> 
this cxx plugin will in a deadlock

**Comment by guwirth** [comment] 2018-11-14 07:03
@liucc52 can you provide the source code creating this issue please.

**Comment by liucc52** [comment] 2018-11-14 07:11
the code contains template like this 
Circle<vc::point> 
if we remove <vc::point>, the scan would be ok

**Comment by guwirth** [comment] 2018-11-14 07:17
@liucc52 maybe duplicate of this #1383?

**Comment by liucc52** [comment] 2018-11-14 07:38
yes, i think it is the same issue with #1383, is this issue resolved?

**Comment by liucc52** [comment] 2018-11-15 09:31
we found this is a bug of sslr, the thread dump show the main thread hang at 
  java.lang.Thread.State: RUNNABLE
	at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:162)
	at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:105)
	at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:61)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:84)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:69)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:94)
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:156)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	- locked <0x00000007022abca8> (a org.sonar.batch.bootstrapper.Batch)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by liucc52** [comment] 2018-11-16 01:01
we resolve this problem by add sonar.cxx.defines=< <,> > to sonar-project.properties

**Comment by guwirth** [comment] 2018-11-16 06:49
@liucc52 thx for your workaround. What exactly did you do? Replacing `<` with `BLANK<`, ...? Question is what happens with shift operators `>>`?

**Comment by guwirth** [comment] 2019-02-09 11:17
see #1685

**Closed by guwirth** 2019-02-09 11:17 UTC
Labels: duplicate, question
