### ISSUE TITLE
Add missing test execution metrics

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1390] opened 2018-01-15 08:49 UTC
Add test execution metrics support.

---
Hint for the missing [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics). The current Wiki information is only valid for SQ5.7
SQ 6.7 has some support for test metrics ([Seeing Tests](https://docs.sonarqube.org/display/SONAR/Seeing+Tests)) but I am not sure whether this works with the C++ Community plug-in.

**Comment by ivangalkin** [comment] 2018-10-26 15:33
I had a brief look at this issue. We have two sensors `CxxUnitTestResultsImportSensor` (Visual Studio, XUnit, NUnit) and `CxxXunitSensor` (custom XML + XSLT), which publish the test-related metrics. They should work as designed:

* both sensors are marked as `global()`, they are executed only on the root-level project
* metrics are published on the root module (project) and should be visible in the corresponding `Measures` tab in the web UI

This technique provides aggregated test metrics for the whole project, no more nor less. A full-fledged solution (when the test metrics are posted on the file granularity) requires a large rework:

* root-modules-only restriction has to be droped: sensor must be executed for each module
* for each file in the test report we have to check, if affected file is located in the analyzed module and (if yes) post the metrics on the **file** level
* metric aggregation is done automatically by the computation engine. So the...
    * aggregation of the metric
    * calcualtion of the test density
    * propagation of metrics from sub-modules to the parent-modules
  ... is done by `org.sonar.ce.task.projectanalysis.step.UnitTestMeasuresStep` (see [here](https://github.com/joansmith/sonarqube/blob/master/server/sonar-server/src/main/java/org/sonar/server/computation/step/UnitTest
  

MeasuresStep.java))

In short, the sensors, which import the test results should be implemented the same way our issue sensors are implemented (cppcheck, clang-tidy etc)

In my opinion this is the only right implementation, but also the very error-prone one. Currently we don't check if the unit-test file is part the analyzed SonarQube project. We just look at the numbers (nr of tests, nr of successfull runs, nr of failed tests etc). Checking if the unit-test file is part of project could be tricky or even impossible (does the report contain a relative path? or are files listed with their names only? it obviously depends on the format of the test report and for the `CxxXunitSensor` the `filename` attribute is de facto **optional**).

I believe, that our "improvement" could break many existing metrics, since previously users didn't care about these aspect.

**Closed** 2020-04-16 15:34 UTC
Labels: enhancement
